### ISSUE TITLE
font face 위치가 이상해요

### ISSUE THREAD

**Issue by chanwoo00106** [SLTDV/Choice-FrontEnd#18]
font face가 globalStyle에 있는 게 좋아 보여요
다른 곳에서도 사용 할 수도 있으니깐

[line link](https://github.com/SLTDV/Choice-FrontEnd/blob/main/src/components/common/Choice/style.ts#L28)

```css
@font-face {
    font-family: 'AppleSDGothicNeoUL';
    font-style: normal;
    src: url('/font/AppleSDGothicNeoUL.woff') format('woff');
  }
```
